# Generated by Django 5.2.16 on 2026-07-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stint_number', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stints', to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stints', to='core.race')),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('lap_time', models.FloatField(blank=True, null=True)),
                ('compound', models.CharField(blank=True, max_length=20)),
                ('is_pit', models.BooleanField(default=False)),
                ('gap_to_front', models.FloatField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='core.race')),
                ('stint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laps', to='core.stint')),
            ],
            options={
                'ordering': ['race', 'driver', 'lap_number'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.team'),
        ),
        migrations.AddConstraint(
            model_name='stint',
            constraint=models.UniqueConstraint(fields=('driver', 'race', 'stint_number'), name='unique_stint_per_driver_race'),
        ),
        migrations.AddIndex(
            model_name='lap',
            index=models.Index(fields=['race', 'driver'], name='core_lap_race_id_bd459d_idx'),
        ),
        migrations.AddIndex(
            model_name='lap',
            index=models.Index(fields=['race', 'compound'], name='core_lap_race_id_5f15a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='lap',
            constraint=models.UniqueConstraint(fields=('driver', 'race', 'lap_number'), name='unique_lap_per_driver_race'),
        ),
    ]
